global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.0.82:9093']

rule_files:
  - "rules.yml"
  - "rules-url.yml"

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['192.168.0.82:9090']

  - job_name: 'central-node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'linux-exporters'
    file_sd_configs:
      - files:
          - linux-targets.json
        refresh_interval: 30s

  - job_name: 'windows-exporters'
    file_sd_configs:
      - files:
          - windows-targets.json
        refresh_interval: 30s

  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
          - cadvisor-targets.json
        refresh_interval: 30s

  - job_name: 'process-exporters'
    file_sd_configs:
      - files:
          - process-targets.json
        refresh_interval: 30s

  - job_name: 'apache-exporters'
    file_sd_configs:
      - files:
          - apache-targets.json
        refresh_interval: 30s

  - job_name: 'elasticsearch-exporters'
    file_sd_configs:
      - files:
          - elasticsearch-targets.json
        refresh_interval: 30s

  # -------- Blackbox Exporter for URL monitoring --------

  - job_name: 'url_monitor'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - /etc/prometheus/url_targets.json
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [module]
        target_label: __param_module
      - target_label: __address__
        replacement: blackbox:9115

