global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'linux-nodes'
    file_sd_configs:
      - files:
          - '/etc/prometheus/linux-targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'windows-nodes'
    file_sd_configs:
      - files:
          - '/etc/prometheus/windows-targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'macos-nodes'
    file_sd_configs:
      - files:
          - '/etc/prometheus/macos-targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - '/etc/prometheus/url_targets.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

